name: deepple_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  go_router: ^16.2.5
  dio: ^5.7.0
  retrofit: ^4.4.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.2
  riverpod_annotation: ^3.0.3
  flutter_screenutil: ^5.9.3
  hive_ce: ^2.15.0
  hive_ce_flutter: ^2.3.2
  path_provider: ^2.1.5
  flutter_svg: ^2.0.16
  gap: ^3.0.1
  infinite_scroll_pagination: ^5.1.1
  table_calendar: ^3.1.3
  file_picker: ^10.3.3
  cached_network_image: ^3.4.1
  fluttertoast: ^9.0.0
  flutter_switch: ^0.3.2
  permission_handler: ^12.0.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  rxdart: ^0.28.0
  in_app_update: ^4.2.3
  package_info_plus: ^8.1.2
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.2
  flutter_dotenv: ^6.0.0
  intl: ^0.20.1
  image: ^4.5.2
  path: ^1.9.0
  mime: ^2.0.0
  http_parser: ^4.1.2
  collection: ^1.19.0
  logger: ^2.5.0
  in_app_purchase: ^3.2.3
  googleapis_auth: ^2.0.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.3.0
  flutter_local_notifications: ^19.5.0
  android_id: ^0.4.0
  device_info_plus: ^12.1.0
  hooks_riverpod: ^3.0.3
  shimmer: ^3.0.0
  equatable: ^2.0.7
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  retrofit_generator: ^10.0.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  json_serializable: ^6.9.0
  go_router_builder: ^4.1.0
  freezed: ^3.2.3
  hive_ce_generator: ^1.9.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/
  fonts:
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: PretendardBold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf
    - family: PretendardSemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.otf
    - family: PretendardMedium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.otf
    - family: PretendardRegular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf

scripts:
  run:
    $before: flutter pub get
    $script: flutter run
  gen:
    build: dart run build_runner build --delete-conflicting-outputs
    watch: dart run build_runner watch --delete-conflicting-outputs

flutter_native_splash:
  image: "assets/images/splash.png"
  color: "#FFFFFF"
  android: false
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  color: "#00000000"
  remove_alpha_ios: true
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  adaptive_icon:
    android: true
    foreground: "assets/images/logo.png"
    background_color: "#00000000"
